# Generated by Django 5.2 on 2025-04-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_custom', models.CharField(editable=False, max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('endereco', models.CharField(max_length=255)),
                ('numero_casa', models.CharField(max_length=10)),
                ('zona_rural', models.BooleanField(default=False)),
                ('telefone1', models.CharField(max_length=15)),
                ('telefone2', models.CharField(blank=True, max_length=15, null=True)),
                ('cartao_produtor', models.CharField(blank=True, max_length=30, null=True)),
                ('checkbox_1', models.BooleanField(default=False)),
                ('checkbox_2', models.BooleanField(default=False)),
                ('checkbox_3', models.BooleanField(default=False)),
                ('checkbox_4', models.BooleanField(default=False)),
                ('relatorio', models.TextField(blank=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('nome', 'cpf')},
            },
        ),
    ]
